# Generated by Django 4.1.1 on 2023-01-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="agendas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("icon", models.CharField(max_length=50)),
                ("status", models.BooleanField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="albums",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("quantty", models.IntegerField(max_length=10)),
                ("size", models.CharField(max_length=30)),
                ("price", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="packages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="pendrives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30)),
                ("capacity", models.CharField(max_length=20)),
                ("price", models.CharField(max_length=30)),
                ("package", models.ManyToManyField(to="shedulle.packages")),
            ],
        ),
        migrations.CreateModel(
            name="videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("duration", models.TimeField()),
                ("format", models.CharField(max_length=30)),
                ("price", models.CharField(max_length=20)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shedulle.packages",
                    ),
                ),
                (
                    "pendrives",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shedulle.pendrives",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="professionals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=30)),
                ("office", models.CharField(max_length=50)),
                ("package", models.ManyToManyField(to="shedulle.packages")),
            ],
        ),
        migrations.CreateModel(
            name="photographs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("size", models.CharField(max_length=30)),
                ("price", models.CharField(max_length=20)),
                ("albums", models.ManyToManyField(to="shedulle.albums")),
                ("package", models.ManyToManyField(to="shedulle.packages")),
                ("pendrives", models.ManyToManyField(to="shedulle.pendrives")),
            ],
        ),
        migrations.CreateModel(
            name="locations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=150)),
                ("contact", models.CharField(max_length=50)),
                ("package", models.ManyToManyField(to="shedulle.packages")),
            ],
        ),
        migrations.CreateModel(
            name="interested",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("source", models.CharField(max_length=50)),
                ("package", models.ManyToManyField(to="shedulle.packages")),
            ],
        ),
        migrations.CreateModel(
            name="frames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("size", models.CharField(max_length=30)),
                ("price", models.CharField(max_length=20)),
                ("package", models.ManyToManyField(to="shedulle.packages")),
            ],
        ),
        migrations.CreateModel(
            name="customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=15)),
                (
                    "interested",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shedulle.interested",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="celebrants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=15)),
                (
                    "customers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shedulle.customers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="calendars_candstudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agendas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shedulle.agendas",
                    ),
                ),
                (
                    "customers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shedulle.customers",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shedulle.packages",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="albums",
            name="package",
            field=models.ManyToManyField(to="shedulle.packages"),
        ),
    ]
