# Generated by Django 4.1.1 on 2023-01-22 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shedulle", "0002_alter_albums_quantty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Celebrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=15)),
                (
                    "Interested",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shedulle.interested",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Photograph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("size", models.CharField(max_length=30)),
                ("price", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Schedule_candstudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shedulle.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("duration", models.TimeField()),
                ("format", models.CharField(max_length=30)),
                ("price", models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(old_name="frames", new_name="Frame",),
        migrations.RenameModel(old_name="locations", new_name="Place",),
        migrations.RenameModel(old_name="professionals", new_name="Professional",),
        migrations.RemoveField(model_name="celebrants", name="customers",),
        migrations.RemoveField(model_name="customers", name="interested",),
        migrations.RemoveField(model_name="photographs", name="albums",),
        migrations.RemoveField(model_name="photographs", name="package",),
        migrations.RemoveField(model_name="photographs", name="pendrives",),
        migrations.RemoveField(model_name="videos", name="package",),
        migrations.RemoveField(model_name="videos", name="pendrives",),
        migrations.RenameModel(old_name="albums", new_name="Album",),
        migrations.RenameModel(old_name="packages", new_name="Package",),
        migrations.RenameModel(old_name="pendrives", new_name="Pendrive",),
        migrations.RenameModel(old_name="agendas", new_name="Schedule",),
        migrations.DeleteModel(name="calendars_candstudio",),
        migrations.DeleteModel(name="celebrants",),
        migrations.DeleteModel(name="customers",),
        migrations.DeleteModel(name="photographs",),
        migrations.DeleteModel(name="videos",),
        migrations.AddField(
            model_name="video",
            name="Pendrive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shedulle.pendrive"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shedulle.package"
            ),
        ),
        migrations.AddField(
            model_name="schedule_candstudio",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shedulle.package"
            ),
        ),
        migrations.AddField(
            model_name="schedule_candstudio",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shedulle.schedule"
            ),
        ),
        migrations.AddField(
            model_name="photograph",
            name="Album",
            field=models.ManyToManyField(to="shedulle.album"),
        ),
        migrations.AddField(
            model_name="photograph",
            name="Pendrive",
            field=models.ManyToManyField(to="shedulle.pendrive"),
        ),
        migrations.AddField(
            model_name="photograph",
            name="package",
            field=models.ManyToManyField(to="shedulle.package"),
        ),
        migrations.AddField(
            model_name="celebrant",
            name="Client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shedulle.client"
            ),
        ),
    ]
